services:
  bot:
    build: .
    volumes:
      # - ./docker_bot:/app
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"